WIP REST API: Job Listings
Automattic/WP-Job-Manager pull request #1060
Opened 2017-06-27 21:06 UTC by pgk

Fixes #

#### Changes proposed in this Pull Request:

*

#### Testing instructions:

*

#### Proposed changelog entry for your changes:

2017-10-12 12:31 UTC, jom requested changes
Overall, it looks really good. Few minor changes requested. Did some testing and works for me.

2017-10-12 12:31 UTC, jom commented on includes/rest-api/class-wp-job-manager-registrable-job-listings.php
> +	 * @param mixed 		  $data Data.
Tabs

2017-10-20 08:12 UTC, pgk commented on mixtape.json
> +{
Good catch! 💯

2017-10-20 08:15 UTC, pgk commented
@jom sorry, this got buried under the mass of PRs, changes made :)

2017-10-20 08:25 UTC, jom approved these changes

2017-10-20 08:38 UTC, merged

2018-05-07 10:39 UTC, Nisha9219 commented
how to access categories plz help me