Added support for Terms & Condition field on Job submission
Automattic/WP-Job-Manager pull request #1922
Opened 2019-10-26 10:58 UTC by akshaya-rane

Fixes #1921

#### Changes proposed in this Pull Request:

* Added 'Terms & Condition' page setting in the Pages tab.
* If the setting is enabled, 'Accept Terms & Condition' checkbox will be displayed on the Job submission page.
* Added validation to accept the Terms & Condition.

#### Testing instructions:

* Set 'Terms & Condition' page in the Settings --> Pages --> Terms & Condition.
* Verify JS & PHP validation on Submit Job page.
* If no page is set for Terms & Condition, there will be no checkbox on Job submission page.

#### Proposed changelog entry for your changes:
Settings for Terms & Condition page. 
Support added for accepting Terms & Condition on the Job submission page.

2020-10-07 14:35 UTC, donnapep requested changes
Thanks for the PR. Before going any further with a review, there are a few things that would need to be cleaned up.

I noticed that this code doesn't currently meet the [PHP coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/), particularly with regards to [whitespace](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage).

Also, this new page setting should also be added to https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-data-cleaner.php, so that it's deleted from the database when the plugin is uninstalled.

2020-10-07 14:35 UTC, donnapep commented on includes/admin/class-wp-job-manager-settings.php
> +                            'label' => __('Terms & Condition Page', 'wp-job-manager'),
Terms & **Conditions** Page

2020-10-07 14:35 UTC, donnapep commented on includes/admin/class-wp-job-manager-settings.php
> +                            'desc'  => __('Select the page where you\'ve placed Terms & Conditions for Job Submission. If this is set it will be shown on Job submission page', 'wp-job-manager'),
How about "When this page is set, a Terms & Conditions checkbox is displayed on the job submission form that must be selected before the form can be submitted."

2020-10-07 14:35 UTC, donnapep commented on includes/forms/class-wp-job-manager-form-submit-job.php
> +     * Use Terms & Condition field on the form?
Why is this a question?

2020-10-07 14:35 UTC, donnapep commented on includes/forms/class-wp-job-manager-form-submit-job.php
> +        $field['label']    = apply_filters('wpjm_terms_field_label', 'Terms & Condition');
Terms & **Conditions**. Also, this should be translatable.

2021-05-28 21:52 UTC, renatho commented
Since this PR is stuck for a while, closing in favor of: https://github.com/Automattic/WP-Job-Manager/pull/2155

2021-05-28 21:52 UTC, closed without merging