fix: decode html special chars for mailto link
Automattic/WP-Job-Manager pull request #2187
Opened 2021-10-14 11:40 UTC by RafaelKr

The german translation for the email subject includes quotes around the job name.

```po
#. translators: %1$s is the job listing title; %2$s is the URL for the current
#. WordPress instance.
#: wp-job-manager-template.php:249
msgid "Application via %1$s listing on %2$s"
msgstr "Bewerbung zum Jobangebot \"%1$s\" auf %2$s"
```

In the email subject this was inserted as `&quot;` instead of `"`. This commit uses htmlspecialchars_decode to fix that.

2022-02-22 20:40 UTC, fjorgemota requested changes
Hey there. Thanks for your contribution! And... also sorry for the delay in the review process.

I suggested using a WordPress function to handle the special chars instead of the native PHP function. It's a tiny detail, but it should be better in the long term.

As soon as you apply the change, I'll approve and merge the PR. :tada: 

Thanks again!

2022-02-22 20:40 UTC, fjorgemota commented on templates/job-application-email.php
> +<p><?php printf( wp_kses_post( __( 'To apply for this job <strong>email your details to</strong> <a class="job_application_email" href="mailto:%1$s%2$s">%1$s</a>', 'wp-job-manager' ) ), esc_html( $ap
This is a very small detail, but..could you please change `htmlspecialchars_decode` to [`wp_specialchars_decode`](https://developer.wordpress.org/reference/functions/wp_specialchars_decode/)? I feel it should be more appropriate for the task, especially as it's a WordPress function that does basically the same task.

Here's my suggestion:

```suggestion
<p><?php printf( wp_kses_post( __( 'To apply for this job <strong>email your details to</strong> <a class="job_application_email" href="mailto:%1$s%2$s">%1$s</a>', 'wp-job-manager' ) ), esc_html( $apply->email ), '?subject=' . rawurlencode( wp_specialchars_decode( $apply->subject, ENT_QUOTES  ) ) ); ?></p>
```

2022-02-23 09:26 UTC, RafaelKr commented
Thanks for your feedback! I implemented your changes.

2022-02-23 13:00 UTC, fjorgemota approved these changes
Looks good and works well! :tada: 

Thanks again for your contribution! I'll merge it. :smiley:

2022-02-23 13:02 UTC, merged

2022-02-23 13:06 UTC, RafaelKr commented
Awesome! :tada: Do you know when the next version will be released?

2022-02-23 13:21 UTC, fjorgemota commented
Hey!

> Do you know when the next version will be released?

I expect the next point release to happen in the coming weeks. I still need to work on some issues, and as soon as I fix them, I'll release a new WPJM version. :smiley:

2022-02-23 13:27 UTC, RafaelKr commented
Okay, but as long as it's included in the next release, which it is, everything is fine 😉
So it's not overwritten by an update

2022-02-23 13:30 UTC, fjorgemota commented
Ah, it'll be included in the next release, for sure. =) 

Thanks again for your contribution. :wink: