Move fields from Writepanels
Automattic/WP-Job-Manager pull request #2288
Opened 2022-07-06 11:42 UTC by onubrooks

Fixes #2286 

### Changes proposed in this Pull Request

* Empty fields array in `WP_Job_Manager_Writepanels` `job_listing_fields()` method.
* Add `_remote_position ` and `_job_salary ` to `WP_Job_Manager_Post_Types::get_job_listing_fields();`

### Testing instructions

* Test that the following snippet works and the fields don't appear on admin:
```
add_filter( 'job_manager_job_listing_data_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

	unset($fields['_company_website']);
	unset($fields['_company_tagline']);
	unset($fields['_company_video']);
	unset($fields['_company_twitter']);
	unset($fields['_company_facebook']);

    return $fields;
}
```

2022-07-06 13:52 UTC, dadish approved these changes

2022-07-06 14:55 UTC, tripflex commented
Thanks @onubrooks there's a few things need to be changed still though, this method should pretty much match what it was before these changes:
https://github.com/Automattic/WP-Job-Manager/blob/1.35.3/includes/admin/class-wp-job-manager-writepanels.php#L55-L129

Mainly these lines:
https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/admin/class-wp-job-manager-writepanels.php#L125-L140

Setting `job_expires` value is already handled in the code below there

2022-07-06 14:56 UTC, tripflex commented
Maybe move this https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/admin/class-wp-job-manager-writepanels.php#L122-L124 to `show_in_admin` for that field?

2022-07-07 20:06 UTC, tripflex approved these changes

2022-07-07 20:06 UTC, tripflex commented on includes/admin/class-wp-job-manager-writepanels.php
>  		}
Code below here needs to be removed, this is already handled (auth checking) when the fields are looped through.

2022-07-07 20:06 UTC, tripflex commented on includes/admin/class-wp-job-manager-writepanels.php
>  		}
[[L125-L148]()](https://github.com/Automattic/WP-Job-Manager/pull/2288/files#diff-f785bb6bb9bc6846adf527dc3cdd73dae3866286bb14c8ec2e7d84b1bb3a396cL125-L148)

2022-07-07 23:31 UTC, fjorgemota requested changes
Looks good overall, but we need to update the test in the file `tests/php/tests/includes/rest-api/test_class.wp-job-manager-job-listings.php` to include the new salary field there too.

2022-07-08 11:28 UTC, onubrooks commented
> Looks good overall, but we need to update the test in the file `tests/php/tests/includes/rest-api/test_class.wp-job-manager-job-listings.php` to include the new salary field there too, [as the tests are currently failing right now](https://github.com/Automattic/WP-Job-Manager/runs/7235523887?check_suite_focus=true).

Fixed in https://github.com/Automattic/WP-Job-Manager/pull/2288/commits/58c9b95a0715d5c2bbdc0a135aa0509bf7321612

2022-07-08 12:55 UTC, fjorgemota approved these changes
Looks good and works well! :tada:

2022-07-08 13:31 UTC, merged