Style settings page header
Automattic/WP-Job-Manager pull request #2641
Opened 2023-11-17 13:13 UTC by yscik

Fixes 163-gh-Automattic/wpjm-addons

Also moved the Save button to the header, because it can be hard to find/remember sometimes when the page is long.
+ Added the styled header to the Marketplace page too.

### Changes Proposed in this Pull Request

* Add a header with logo to the Settings and Marketplace changes
* Tweak some colors and spacing, set max width
* Move the Save Changes button to the header, make it change color when there are changes to save
* Fix some scroll jumping
* Fix search in the Marketplace page going to the old `..-addons` URL
* Update the outdated lost license link in the License page

### Testing Instructions

* Open the Job Manager → Settings page, click around, change some settings, make sure everything works right
* Also check out the Job Manager → Marketplace page

### Release Notes

* Update design for settings and marketplace pages

### Screenshot / Video

![image](https://github.com/Automattic/WP-Job-Manager/assets/176949/4450807b-e21b-4a8f-98aa-75a9ace8b0a7)

![image](https://github.com/Automattic/WP-Job-Manager/assets/176949/f9831193-ec39-459d-80b6-b1d5c9e25c8b)

2023-11-17 17:04 UTC, masteradhoc commented
Looks great @yscik!

2023-11-17 19:17 UTC, mikeyarce requested changes
Looks great @yscik !

Added a few small escaping things.

I also found one small issue - which I think are actually not new but might be good to address?

When in a mobile view, if you click on something like "Job Submission" - there's a `margin-bottom: 1px` which is pushing the other elements below it:
![CleanShot 2023-11-17 at 11 07 29@2x](https://github.com/Automattic/WP-Job-Manager/assets/3220162/e8da7b71-b2cd-4c83-8c48-cc9262437895)

This CSS seems to fix it:

```
.nav-tab.nav-tab-active {
  margin-bottom: 0;
}
```

2023-11-17 19:17 UTC, mikeyarce commented on includes/admin/class-wp-job-manager-addons.php
> +							src="<?php echo esc_attr( JOB_MANAGER_PLUGIN_URL . '/assets/images/jm-full-logo.png' ); ?>"
This should be `esc_url()` here.

2023-11-17 19:17 UTC, mikeyarce commented on includes/admin/class-wp-job-manager-settings.php
> +								src="<?php echo esc_attr( JOB_MANAGER_PLUGIN_URL . '/assets/images/jm-full-logo.png' ); ?>"
Should be `esc_url()` here.

2023-11-17 19:17 UTC, mikeyarce commented on includes/admin/class-wp-job-manager-settings.php
> +								echo '<a href="#settings-' . esc_attr( sanitize_title( $key ) ) . '" class="nav-tab">' . esc_html( $section[0] ) . '</a>';
`esc_url()` here, too.  Probably best to wrap the whole URL inside `esc_url()` though.  

Something like
```
echo '<a href="' . esc_url( '#settings-' . sanitize_title( $key ) ) . '" class="nav-tab">' . esc_html( $section[0] ) . '</a>';
```

2023-11-20 13:05 UTC, yscik commented
Thanks! Improved the escaping and did some fixes for mobile, with smaller logo, non-sticky header and a save button in the bottom.

![image](https://github.com/Automattic/WP-Job-Manager/assets/176949/88c89638-8757-4d8d-b664-997cfab88ff0)

2023-11-20 21:32 UTC, mikeyarce approved these changes
Looks really good! 🎉

2023-11-28 18:03 UTC, merged