Set the default dateFormat if it’s empty
Automattic/WP-Job-Manager pull request #2779
Opened 2024-02-24 00:40 UTC by mikeyarce

Fixes https://github.com/Automattic/WP-Job-Manager/issues/2739

### Changes Proposed in this Pull Request

* Previously, we were setting a datepicker option if it was empty, but it was causing some issues with showing the dateformat in the editor.  Now, this will just set the default in case the default dateFormat is empty.
* Bonus: also added a fallback for the main Jobs view in case there is no DateFormat

### Testing Instructions

* Settings > General - set the Date Format to `Custom`, clear out the custom format and save.
* Go to a Job Listing, make sure you can save an expiry date
* Refresh to make sure it's still there!
* Go to the Jobs page and make sure you see the dates in the column view as well.
* Do the same thing now but select a Date Format of your choosing!

### Release Notes

* Fix: Expiry date not showing up in backend editor.
* Fix: Add fallback to date format for Jobs view in case it's missing.

2024-02-28 09:02 UTC, thedebian requested changes
I think we might need to update somewhere all components of WPJM and addons could check, here is an example of places it wasn't working properly:

![Capture d’écran 2024-02-28 à 09 58 44](https://github.com/Automattic/WP-Job-Manager/assets/1420594/df92a3d3-8069-478d-a073-0d851e57ce35)

![Capture d’écran 2024-02-28 à 10 00 02](https://github.com/Automattic/WP-Job-Manager/assets/1420594/cb6575e3-5e91-4cf5-bab0-87327b8065da)

The input for some reasons is also empty, while the date is there (it's also an issue when a proper date format is in general settings, so it might be an old bug):

![Capture d’écran 2024-02-28 à 09 59 24](https://github.com/Automattic/WP-Job-Manager/assets/1420594/b6d63c1c-24dd-4175-8b51-e58b16348171)

If I update the date format in general settings the date appears properly:

![Capture d’écran 2024-02-28 à 10 00 44](https://github.com/Automattic/WP-Job-Manager/assets/1420594/cd74e894-3775-4a35-a0bf-df89bedcd488)

2024-03-05 19:01 UTC, mikeyarce commented
Thanks @thedebian - my initial PR was addressing the problem when jQuery UI was missing the format, but now I've expanded that to add a fallback for when the actual `get_option( 'date_format' )` is missing in the rest of the plugin 😄

2024-03-13 08:28 UTC, thedebian approved these changes
Looking good.
Not a blocker, but if we can put 'F j, Y' in a constant somewhere, it'd probably be better.

2024-03-14 18:39 UTC, merged

2024-03-23 08:27 UTC, ibiza69 commented
Hello, we updated the plugin with the patch provided on github and it completely broke our website, both the front and backend, without the possibility of access to both. We have had to download the original plugin (not the one patched at github), version 2.2.2 from WordPress and upload it via FTP, overwriting the files, in order to solve the problem.

2024-04-03 16:46 UTC, mikeyarce commented
Hi @ibiza69 - did you just download the source or did you also run the build steps?  The safest bet would be to wait till we have a release and test that!

2024-04-03 19:04 UTC, ibiza69 commented
Hi @mikeyarce, we downloaded thru github the fix and uploaded the files thru FTP and that crashed our site. 

We shall wait untill plugin update at wordpress :) Thank you.