Allow linking to specific settings tab via hash in URL
Automattic/WP-Job-Manager pull request #999
Opened 2017-05-26 00:45 UTC by tripflex

Fixes #993 

#### Changes proposed in this Pull Request:

* Allow linking to specific settings tab via hash in URL

#### Testing instructions:

* Goto settings page, copy URL from one of the tabs, go to some other non-settings page, enter the URL with the hash, voila!

2017-05-31 16:53 UTC, pbearne commented
Is a click() call the right way do this

We did it this way in a plugin we are working on

```
			jQuery(function(){

              var tabsIds = jQuery('.job-manager-settings-wrap div').toArray().map(function(value) { return '#' + value.id } );

              if((tabsIds.indexOf(window.location.hash) > -1)) {

                jQuery('.nav-tab-wrapper a[href="#settings-job_listings"]').removeClass('nav-tab-active');
                jQuery('.settings_panel').css('display', 'none');

                jQuery('.nav-tab-wrapper a[href="' + window.location.hash + '"]').addClass('nav-tab-active');
                jQuery('div' + window.location.hash).css('display', 'block');
              }
			}); 
```

2017-05-31 22:20 UTC, jom requested changes
This seems like a sensible solution. One wee fix and then it is good to merge. Thanks, Myles!

2017-05-31 22:20 UTC, jom commented on includes/admin/class-wp-job-manager-settings.php
> +				if ( the_tab ) {
This should be:
`if ( the_tab.length > 0 ) {`

jQuery's selector will always return an object that would evaluate `true` in the current line.

2017-06-08 15:36 UTC, tripflex commented on includes/admin/class-wp-job-manager-settings.php
> +				if ( the_tab ) {
Yup you're correct, updated the PR

2017-06-09 13:10 UTC, jom approved these changes

2017-06-19 12:07 UTC, merged